# Generated by Django 4.2.1 on 2023-06-03 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='house',
            new_name='house_number',
        ),
    ]
